/*
 * This source file was generated by the Gradle 'init' task
 */
package validate_sa_id;

import org.junit.jupiter.api.Test;

import validate_sa_id.ValidateSaId;

import static org.junit.jupiter.api.Assertions.*;

class ValidateSaIdTest {
    @Test
    public void testValidIdNumber() {
        String validId = "2909035800085";
        assertTrue(ValidateSaId.isIdNumberValid(validId));
    }

    @Test
    void isInValidCitizenship() {
        assertTrue(ValidateSaId.isIdNumberValid("2001014800286")); // invalid citizenship digit
    }
}
