/*
 * This source file was generated by the Gradle 'init' task
 */
package validate_sa_id;

import org.junit.jupiter.api.Test;

import validate_sa_id.ValidateSaId;

import static org.junit.jupiter.api.Assertions.*;

class ValidateSaIdTest {
    
}
