/*
 * This source file was generated by the Gradle 'init' task
 */
package validate_sa_id;

import org.junit.jupiter.api.Test;

import validate_sa_id.ValidateSaId;

import static org.junit.jupiter.api.Assertions.*;

class ValidateSaIdTest {
    
    @Test
    void testValidIdNumber() {
        System.out.println("\n=== Testing Valid ID Number ===");
        String validId = "2001014800086";
        boolean result = ValidateSaId.isIdNumberValid(validId);
        System.out.println("Test Result: " + (result ? "PASSED" : "FAILED"));
        assertTrue(result);
    }

    @Test
    void testNullInput() {
        System.out.println("\n=== Testing Null Input ===");
        boolean result = ValidateSaId.isIdNumberValid(null);
        System.out.println("Test Result: " + (!result ? "PASSED" : "FAILED"));
        assertFalse(result);
    }
    @Test
    void testShortIdNumber() {
        System.out.println("\n=== Testing Short ID Number ===");
        String shortId = "200101480008";
        boolean result = ValidateSaId.isIdNumberValid(shortId);
        System.out.println("Test Result: " + (!result ? "PASSED" : "FAILED"));
        assertFalse(result);
    }

    @Test
    void testLongIdNumber() {
        System.out.println("\n=== Testing Long ID Number ===");
        String longId = "20010148000867";
        boolean result = ValidateSaId.isIdNumberValid(longId);
        System.out.println("Test Result: " + (!result ? "PASSED" : "FAILED"));
        assertFalse(result);
    }
    @Test
    void testNonNumericIdNumber() {
        System.out.println("\n=== Testing Non-Numeric ID Number ===");
        String nonNumericId = "20010A4800086";
        boolean result = ValidateSaId.isIdNumberValid(nonNumericId);
        System.out.println("Test Result: " + (!result ? "PASSED" : "FAILED"));
        assertFalse(result);
    }


    
}
