/*
 * This source file was generated by the Gradle 'init' task
 */
package validate_sa_id;

public class ValidateSaId {
    public static boolean isIdNumberValid(String idNumber) {
        if (idNumber.length() != 13) {
            return false;
        }
        return true;
    }

    private static boolean isValidCitizenship(String idNumber) {
        int citizenshipDigit = Integer.parseInt(idNumber.substring(10, 11));
        return citizenshipDigit == 0 || citizenshipDigit == 1;
    }
}
